version: "3"

services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      - DB_HOST=postgres  # networking: containers are available to each other via hostnames named after their service name
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - EMAIL_HOST=mailhog
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src  # Mounting our source and test code as volumes means we don’t need to rebuild our containers every time we make a code change.
      - ./tests:/tests
    entrypoint:
      - python
      - /src/allocation/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    depends_on:
      - redis_pubsub
      - mailhog
    env_file:
      - container.env
    environment:
      - API_HOST=api
      - FLASK_APP=allocation/entrypoints/flask_app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1  # tells Python to not write .pyc files
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"

  redis:  # Inside Docker, other containers are available through hostnames named after their service name. Outside Docker, they are available on localhost, at the port defined in the ports section.
    image: redis:alpine
    ports:  # The ports section allows us to expose the ports from inside the containers to the outside world —these correspond to the default ports we set in config.py.
      - "63791:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "11025:1025"
      - "18025:8025"
